#
# see https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
#
name: '"Build Tutor Backup & Restore Plugin" Action For GitHub Actions'
description: 'Build a Docker container for the hastexo Backup plugin and upload to AWS ECR'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  AWS_ECR_REGISTRY:
    description: 'The URI of the AWS Elastic Container Registry (ECR). Example 012345678912.dkr.ecr.us-east-2.amazonaws.com'
    required: true
  AWS_ECR_REPOSITORY:
    description: 'The name of the repository inside your AWS Elastic Container Registry (ECR) in which the newly created container will be uploaded and tagged. Defaults to "openedx_backup"'
    required: false
    default: 'openedx_backup'
  HASTEXO_BACKUP_RELEASE:
    description: 'the release of https://github.com/hastexo/tutor-contrib-backup'
    required: false
    default: 'v0.0.6'
outputs:
  docker-container-url:
    description: 'The URL of the AWS ECR Docker container that was created and uploaded'
    value: ${DOCKER_IMAGE}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      id: setup-docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Install Tutor
      id: install-tutor
      run: $GITHUB_ACTION_PATH/scripts/install-tutor.sh
      shell: bash

    - name: Set repository tag
      id: docker-set-tag
      run: |
        echo "REPOSITORY_TAG=$TUTOR_VERSION-$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      shell: bash

    - name: Install hastexo Backup plugin
      id: pip-install-plugin
      run: $GITHUB_ACTION_PATH/scripts/install-hastexo-backup.sh
      shell: bash

    - name: Build the image
      id: tutor-build-image
      run: tutor images build backup
      shell: bash

    - name: Push the image
      id: docker-push-image
      run: $GITHUB_ACTION_PATH/scripts/upload-to-aws-ecr.sh
      shell: bash

    - name: Docker image:tag
      id: docker-image
      run: |
        echo "DOCKER_IMAGE=${AWS_ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${REPOSITORY_TAG}" >> $GITHUB_ENV
      shell: bash
